import { createFileRoute } from '@tanstack/react-router'

import { MarketTable } from '../../components/MarketTable'
import { MarketDataResponse } from '../../types/market'

export const Route = createFileRoute('/components/market')({
  component: Index,
})

function Index() {
  const data: MarketDataResponse = {
    timestamp: 1718989486,
    itemname: '',
    itemid: 0,
    datacenter: 'Meteor',
    data: {
      Belias: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Belias',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Belias',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Belias',
          },
        ],
      },
      Mandragora: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Mandragora',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Mandragora',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Mandragora',
          },
        ],
      },
      Ramuh: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Ramuh',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Ramuh',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Ramuh',
          },
        ],
      },
      Shinryu: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Shinryu',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Shinryu',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Shinryu',
          },
        ],
      },
      Unicorn: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Unicorn',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Unicorn',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Unicorn',
          },
        ],
      },
      Valefor: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Valefor',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Valefor',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Valefor',
          },
        ],
      },
      Yojimbo: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Yojimbo',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Yojimbo',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Yojimbo',
          },
        ],
      },
      Zeromus: {
        date: 1718989486,
        entries: [
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 4,
            sellPrice: 389980,
            sellRetainerName: 'Pine-tree',
            signatureName: 'Takapi Poppo',
            stack: 1,
            stain: 0,
            total: 389980,
            world: 'Zeromus',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 0,
            materia1: '',
            materia2: '',
            materia3: '',
            materia4: '',
            materia5: '',
            registerTown: 2,
            sellPrice: 390000,
            sellRetainerName: 'Kirakiramofu',
            signatureName: 'Haru Mofu',
            stack: 1,
            stain: 0,
            total: 390000,
            world: 'Zeromus',
          },
          {
            Updated: 1718989486,
            hq: 1,
            isCrafted: 1,
            materia: 5,
            materia1: 26729,
            materia2: 26729,
            materia3: 26729,
            materia4: 25188,
            materia5: 25188,
            registerTown: 4,
            sellPrice: 1200000,
            sellRetainerName: 'Azlina',
            signatureName: 'Sifr Avery',
            stack: 1,
            stain: 0,
            total: 1200000,
            world: 'Zeromus',
          },
        ],
      },
    },
  }
  return (
    <div style={{ width: '100%', height: '50vh' }}>
      <MarketTable data={data.data} />
    </div>
  )
}
